language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -U pip
  - pip install isort flake8 coveralls
  - pip install -e git+https://github.com/shuup/shuup.git@master#egg=shuup[everything]
  - pip install -e .
script:
  - isort --check-only
  - flake8
  - py.test -ra -vvv --cov-config .coveragerc --cov shuup_graphql shuup_graphql_tests
after_success: coveralls
